name: Build with Gradle

on:
  push:
    branches: [1.20.2]
  pull_request:
    branches: [1.20.2]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Make sure the `./gradlew` is executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Double check the Tests
        run: ./gradlew allTests
