# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.3

# Mod Properties
mod_version=0.15.0-dev
maven_group=nordmods
archives_base_name=uselessreptile

# Dependencies
fabric_version=0.155.2+26.1.2
yacl_version=3.9.0+26.1
modmenu_version=18.0.0-alpha.6
protection_api_version=2.0.0
primitive_multipart_entities_version=1.4.2-26.1.2
biscuit_roll_version=0.19.0-dev-26.1.2
jade_version=26.0.3


